Fix mobile right scroll
eightalex/venus pull request #5
Opened 2024-10-21 16:42 UTC by radoshDev

2024-10-21 18:02 UTC, eightalex commented
Зміни тільки в CSS файлі, потрібно змінити все в SCSS, а на SCSS налаштувати File Watcher

2024-10-22 11:37 UTC, eightalex requested changes

2024-10-22 11:37 UTC, eightalex commented on styles/_variables.scss
> +$small-mobile-breakpoint: 400px;
У нас тепер брейкпоінти є в міксіні, а також в змінних, бажано тримати все в одному місці. І якщо ця змінна використовується тільки один раз, то не зрозуміло навіщо вона потрібна

2024-10-22 11:37 UTC, eightalex commented on styles/_variables.scss
> +$small-mobile-subtitle-font-size: 20px;
Є питання до неймінгу. Наприклад якщо додадуться ще змінні, припустимо, менше ніж small, як ти його назвеш? Також small і mobile — поняття дублюють одне одного. І бажано групувати по сутності а не по значенню (головніше ставити на початку назви):

```
$font-size-title-s: 30px;
$font-size-subtitle-s: 20px;
```

Приклад, якщо ще щось треба буде додати:

```
$font-size-title-xs: 24px;
$font-size-title-s: 30px;
$font-size-subtitle-xs: 16px;
$font-size-subtitle-s: 20px;
```

Я пропоную структурувати змінні за їх важливістю та роллю в дизайні. Наприклад, спочатку — розмір тексту, потім — контекст (title, subtitle), і лише після цього — розмір екрана (якщо потрібно)

2024-10-23 12:58 UTC, radoshDev commented on styles/_variables.scss
> +$small-mobile-breakpoint: 400px;
Та наче не в одному місці використовується, а в 7 файлах. Можу додати ще один if в міксін `bp`, але мені виглядає в змінній найгнучкіше, бо можливо в майбутньому її треба буде збільшити, якщо інший текст не буде поміщатись

2024-10-23 17:33 UTC, eightalex commented
Треба пофіксити конфлікти

2024-10-25 09:31 UTC, merged