Custom field for dates and author in taxonomy
eightalex/venus pull request #8
Opened 2024-10-24 14:56 UTC by radoshDev

Вийшло багато файлів, бо я змерджив feature/publication-date в цю гілку

2024-10-25 12:58 UTC, eightalex requested changes

2024-10-25 12:58 UTC, eightalex commented on theme-parts/modules/post-info.php
> +            <?php if ($post_published_date) {?>
Вище вже є перевірка на $post_published_date, ця перевірка нічого не робить

2024-10-25 12:58 UTC, eightalex commented on styles/blocks/_post-info.scss
> +		}
В файлі знову полізли відступи

2024-10-25 13:01 UTC, eightalex commented on theme-parts/modules/post-info.php
> +    }));
Тут є проблема. Функція array_shift очікує отримати посилання на змінну (тобто сам масив, переданий за посиланням), а не результат, який повертається іншою функцією, як у випадку з array_filter.

Функції array_shift (як і деяким іншим функціям, наприклад, array_pop) потрібно посилання на змінну замість результату функції, тому що вона змінює сам масив. Це не просто функція, яка повертає значення — вона також модифікує оригінальний масив, видаляючи його перший елемент.

Як це виправити:

```suggestion
    $filtered_array = array_filter($tax_content, function($part) {
        return isset($part['_type']) && $part['_type'] === 'author';
    });

    $author = array_shift($filtered_array);
```

2024-10-27 15:48 UTC, radoshDev commented on styles/blocks/_post-info.scss
> +		}
Виправив

2024-10-27 15:48 UTC, radoshDev commented on theme-parts/modules/post-info.php
> +            <?php if ($post_published_date) {?>
Виправив

2024-10-29 13:49 UTC, merged